# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Poketrader' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Poketrader
  pod 'Alamofire', '~> 5.2'
  pod 'lottie-ios'
  pod 'IQKeyboardManagerSwift'
  pod 'PasswordTextField'
  pod 'SCLAlertView'
  # Pods do Firebase
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
end
